## 1. Import necessary Libraries

In [33]:
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score
import pickle as pkl

## 2. Load the dataset

In [15]:
california_housing_data=datasets.fetch_california_housing()
california_housing_data_df=pd.DataFrame(data=california_housing_data.data,columns=california_housing_data.feature_names)
california_housing_data_df["target"] = california_housing_data.target
california_housing_data_df

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  target
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23   4.526
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22   3.585
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24   3.521
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25   3.413
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25   3.422
...       ...       ...       ...        ...         ...       ...       ...        ...     ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48    -121.09   0.781
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49    -121.21   0.771
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43    -121.22   0.923
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43    -121.32   0.847
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37    -121.24   0.894

[20640 rows x 9 columns]

In [16]:
california_housing_data_df

       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  target
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23   4.526
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22   3.585
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24   3.521
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25   3.413
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25   3.422
...       ...       ...       ...        ...         ...       ...       ...        ...     ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48    -121.09   0.781
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49    -121.21   0.771
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43    -121.22   0.923
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43    -121.32   0.847
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37    -121.24   0.894

[20640 rows x 9 columns]

## 3. Data Understanding

In [22]:
california_housing_data_df.head()

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  target
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23   4.526
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22   3.585
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24   3.521
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25   3.413
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25   3.422

In [23]:
california_housing_data_df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
target        0
dtype: int64

In [24]:
california_housing_data_df.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
target        float64
dtype: object

In [25]:
california_housing_data_df.describe()

             MedInc      HouseAge      AveRooms     AveBedrms  ...      AveOccup      Latitude     Longitude        target
count  20640.000000  20640.000000  20640.000000  20640.000000  ...  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675  ...      3.070655     35.631861   -119.569704      2.068558
std        1.899822     12.585558      2.474173      0.473911  ...     10.386050      2.135952      2.003532      1.153956
min        0.499900      1.000000      0.846154      0.333333  ...      0.692308     32.540000   -124.350000      0.149990
25%        2.563400     18.000000      4.440716      1.006079  ...      2.429741     33.930000   -121.800000      1.196000
50%        3.534800     29.000000      5.229129      1.048780  ...      2.818116     34.260000   -118.490000      1.797000
75%        4.743250     37.000000      6.052381      1.099526  ...      3.282261     37.710000   -118.010000      2.647250
max       15.000100     52.000000    141.909091     34.066667  ...   1243.333333     41.950000   -114.310000      5.000010

[8 rows x 9 columns]

## 4. Data Preparation

In [17]:
X=california_housing_data_df.drop(labels="target",axis=1)

In [18]:
y=california_housing_data_df["target"]

## 5. Model building || 6. Model Training

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,shuffle=True,random_state=42)

In [35]:
gradientboosting_model = GradientBoostingRegressor(max_depth=3, n_estimators=50, learning_rate=1.0,)
gradientboosting_model.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=1.0, n_estimators=50)

## 7. Model Testing || 8. Model Evaluation

### Training data

In [36]:
y_pred_train = gradientboosting_model.predict(X_train)

In [37]:
print("Mean absolute error:",mean_absolute_error(y_train,y_pred_train))
print("Mean squared error:",mean_squared_error(y_train,y_pred_train))
print("Root mean absolute error:",root_mean_squared_error(y_train,y_pred_train))
print("r2 score:",r2_score(y_train,y_pred_train))

Mean absolute error: 0.32286512231080355
Mean squared error: 0.20757011043802392
Root mean absolute error: 0.45559862866126355
r2 score: 0.8447235984193906

### Test Data

In [38]:
y_pred_test = gradientboosting_model.predict(X_test)

In [40]:
print("Mean absolute error:",mean_absolute_error(y_test,y_pred_test))
print("Mean squared error:",mean_squared_error(y_test,y_pred_test))
print("Root mean absolute error:",root_mean_squared_error(y_test,y_pred_test))
print("r2 score:",r2_score(y_test,y_pred_test))

Mean absolute error: 0.366736097424734
Mean squared error: 0.28969732423995637
Root mean absolute error: 0.5382353799593226
r2 score: 0.7789260230582

## 9. Model deployment - export the model

In [41]:
pkl.dump(gradientboosting_model,open("gradientboosting_model.pkl","wb"))