## 1. Import necessary Libraries

In [1]:
import pandas as pd

## 2. Import Dataset

In [3]:
movies_data=pd.read_csv("Movie.csv")
movies_data

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

## 3. Data Understanding

In [4]:
movies_data.shape

(8992, 3)

In [5]:
movies_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [6]:
movies_data.dtypes

userId      int64
movie      object
rating    float64
dtype: object

In [8]:
movies_data.describe(include="all")

             userId             movie       rating
count   8992.000000              8992  8992.000000
unique          NaN                10          NaN
top             NaN  Toy Story (1995)          NaN
freq            NaN              2569          NaN
mean    3521.880116               NaN     3.557162
std     2012.497384               NaN     0.967071
min        1.000000               NaN     0.500000
25%     1779.000000               NaN     3.000000
50%     3530.000000               NaN     3.500000
75%     5213.250000               NaN     4.000000
max     7120.000000               NaN     5.000000

In [9]:
movies_data["movie"].unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

## 4. Data Preparation || 5. Model Building

### 4.1  Building UBCF using Pearson CorrelationMethod

In [10]:
movies_data.head(2)

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0

In [14]:
pivot_table=pd.pivot_table(data=movies_data,values="rating",index="movie",columns="userId").fillna(0)
pivot_table.columns=movies_data["userId"].unique()
pivot_table

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sudden Death (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Toy Story (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
# method: 'CorrelationMethod' = 'pearson', values between -1 to +1
pivot_table.corr().round(3)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
6,-0.111,1.000,-0.111,-0.165,-0.111,0.276,0.667,0.564,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,-0.167,-0.111,-0.166,0.351,-0.111,-0.218
8,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
10,-0.165,-0.165,-0.165,1.000,-0.165,-0.313,-0.247,0.484,-0.165,0.245,...,0.776,-0.165,-0.165,-0.247,0.987,-0.165,-0.246,0.483,-0.165,-0.322
11,1.000,-0.111,-0.111,-0.165,1.000,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,1.000,0.667,-0.167,-0.111,-0.166,-0.351,-0.111,0.479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,-0.111,-0.111,-0.111,-0.165,-0.111,-0.211,-0.167,-0.265,-0.111,-0.159,...,-0.111,-0.111,-0.111,-0.167,-0.167,1.000,0.609,-0.351,-0.111,-0.218
7070,-0.166,-0.166,0.720,-0.246,-0.166,0.332,-0.249,0.132,0.720,0.577,...,-0.166,0.720,-0.166,0.416,-0.249,0.609,1.000,0.035,0.720,0.300
7080,-0.351,0.351,0.351,0.483,-0.351,0.539,0.395,0.813,0.351,0.412,...,0.176,0.351,-0.351,0.000,0.527,-0.351,0.035,1.000,0.351,0.138
7087,-0.111,-0.111,1.000,-0.165,-0.111,0.601,-0.167,0.398,1.000,0.862,...,-0.111,1.000,-0.111,0.667,-0.167,-0.111,0.720,0.351,1.000,0.566
7105,0.479,-0.218,0.566,-0.322,0.479,0.668,0.196,-0.052,0.566,0.409,...,-0.218,0.566,0.479,0.784,-0.327,-0.218,0.300,0.138,0.566,1.000

In [20]:
movies_data[(movies_data["userId"]==3) | (movies_data["userId"]==11)]

      userId             movie  rating
0          3  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

### 4.2. Building UBCF using Euclideon Distance

In [22]:
from sklearn.metrics import pairwise_distances

In [24]:
movies_data.head(5)

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [29]:
euclideon_pivot_table=pd.pivot_table(data=movies_data,values="rating",index="userId",columns="movie").fillna(0)
euclideon_pivot_table.columns=movies_data["movie"].unique()
euclideon_pivot_table.index=movies_data["userId"].unique()
euclideon_pivot_table

,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7070,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7080,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7105,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [32]:
eculideon_correlation=pd.DataFrame(pairwise_distances(X=euclideon_pivot_table,metric='euclidean'))
eculideon_correlation.index=movies_data["userId"].unique()
eculideon_correlation.columns=movies_data["userId"].unique()
eculideon_correlation

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,...,4.031129,5.315073,1.500000,4.031129,5.500000,5.315073,6.363961,9.394147,6.103278,6.041523
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,5.656854,6.652067,7.745967,6.403124,8.261356
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,...,3.605551,6.403124,5.385165,7.549834,1.000000,6.403124,7.297260,6.855655,7.071068,8.789198
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,...,3.605551,5.000000,1.000000,4.123106,5.196152,5.000000,6.103278,9.219544,5.830952,6.103278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,5.315073,5.656854,5.656854,6.403124,5.000000,8.660254,5.830952,9.055385,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,0.000000,4.031129,9.591663,6.403124,8.261356
7070,6.363961,6.652067,3.500000,7.297260,6.103278,6.873864,6.800735,7.889867,3.500000,4.330127,...,5.678908,3.500000,5.678908,5.315073,6.800735,4.031129,0.000000,8.500000,3.640055,6.670832
7080,9.394147,7.745967,7.745967,6.855655,9.219544,6.403124,7.211103,4.000000,7.745967,7.176350,...,8.246211,7.745967,8.944272,8.717798,6.782330,9.591663,8.500000,0.000000,7.810250,8.261356
7087,6.103278,6.403124,1.000000,7.071068,5.830952,5.830952,6.557439,7.141428,1.000000,2.549510,...,5.385165,1.000000,5.385165,4.123106,6.557439,6.403124,3.640055,7.810250,0.000000,5.678908
7105,6.041523,8.261356,5.678908,8.789198,6.103278,5.123475,6.800735,9.069179,5.678908,6.184658,...,7.500000,5.678908,6.344289,4.031129,8.381527,8.261356,6.670832,8.261356,5.678908,0.000000

## 4.3. Building UBCF using Cosine Similarity

In [33]:
eculideon_correlation=pd.DataFrame(pairwise_distances(X=euclideon_pivot_table,metric='cosine'))
eculideon_correlation.index=movies_data["userId"].unique()
eculideon_correlation.columns=movies_data["userId"].unique()
eculideon_correlation

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,0.292893,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,4.466284e-01
6,1.000000,0.000000,1.000000,1.000000,1.000000,0.609433,0.292893,0.384543,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,5.411685e-01,1.000000,1.000000e+00
8,1.000000,1.000000,0.000000,1.000000,1.000000,0.349055,1.000000,0.507634,0.000000,0.125843,...,1.000000,0.000000,1.000000,0.292893,1.000000,1.000000,2.474233e-01,5.411685e-01,0.000000,3.774570e-01
10,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.384543,1.000000,0.611486,...,0.200000,1.000000,1.000000,1.000000,0.010051,1.000000,1.000000e+00,3.805775e-01,1.000000,1.000000e+00
11,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,0.292893,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,4.466284e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.414954e-01,1.000000e+00,1.000000,1.000000e+00
7070,1.000000,1.000000,0.247423,1.000000,1.000000,0.510114,1.000000,0.629457,0.247423,0.342130,...,1.000000,0.247423,1.000000,0.467848,1.000000,0.341495,1.110223e-16,6.546941e-01,0.247423,5.314886e-01
7080,1.000000,0.541169,0.541169,0.380578,1.000000,0.298116,0.432225,0.110468,0.541169,0.431788,...,0.655876,0.541169,1.000000,0.675557,0.351114,1.000000,6.546941e-01,1.110223e-16,0.541169,5.239295e-01
7087,1.000000,1.000000,0.000000,1.000000,1.000000,0.349055,1.000000,0.507634,0.000000,0.125843,...,1.000000,0.000000,1.000000,0.292893,1.000000,1.000000,2.474233e-01,5.411685e-01,0.000000,3.774570e-01
7105,0.446628,1.000000,0.377457,1.000000,0.446628,0.234545,0.608707,0.693481,0.377457,0.455799,...,1.000000,0.377457,0.446628,0.168503,1.000000,1.000000,5.314886e-01,5.239295e-01,0.377457,1.110223e-16

### Analyse for first 20 observation

In [51]:
eculideon_correlation.iloc[:20,:20]
eculideon_correlation.loc[:39,:39]

,3,6,8,10,11,12,13,14,16,19,22,23,24,31,34,39
3,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,4.855042e-01,1.000000,1.000000,1.000000,1.000000
6,1.000000,0.000000,1.000000,1.000000,1.000000,0.609433,0.292893,3.845425e-01,1.000000,1.000000e+00,0.562405,1.000000e+00,1.000000,1.000000,1.000000,1.000000
8,1.000000,1.000000,0.000000,1.000000,1.000000,0.349055,1.000000,5.076340e-01,0.000000,1.258427e-01,0.416540,3.140057e-01,0.210648,1.000000,0.292893,1.000000
10,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,3.845425e-01,1.000000,6.114857e-01,0.737443,5.884034e-01,1.000000,0.200000,0.575736,0.400000
11,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,1.000000,4.855042e-01,1.000000,1.000000,1.000000,1.000000
12,1.000000,0.609433,0.349055,1.000000,1.000000,0.000000,0.263540,4.391198e-01,0.349055,4.309721e-01,0.164440,5.534557e-01,0.086534,1.000000,0.539713,1.000000
13,1.000000,0.292893,1.000000,1.000000,1.000000,0.263540,0.000000,5.648059e-01,1.000000,1.000000e+00,0.381147,1.000000e+00,0.565878,1.000000,1.000000,1.000000
14,1.000000,0.384543,0.507634,0.384543,1.000000,0.439120,0.564806,1.110223e-16,0.507634,3.304807e-01,0.281810,4.089195e-01,0.611350,0.507634,0.390728,0.630726
16,1.000000,1.000000,0.000000,1.000000,1.000000,0.349055,1.000000,5.076340e-01,0.000000,1.258427e-01,0.416540,3.140057e-01,0.210648,1.000000,0.292893,1.000000
19,1.000000,1.000000,0.125843,0.611486,1.000000,0.430972,1.000000,3.304807e-01,0.125843,1.110223e-16,0.489964,1.504718e-01,0.309982,0.514357,0.381877,1.000000
22,1.000000,0.562405,0.416540,0.737443,1.000000,0.164440,0.381147,2.818104e-01,0.416540,4.899642e-01,0.000000,5.997498e-01,0.270787,1.000000,0.278005,0.562405
23,0.485504,1.000000,0.314006,0.588403,0.485504,0.553456,1.000000,4.089195e-01,0.314006,1.504718e-01,0.599750,2.220446e-16,0.458509,0.485504,0.514929,1.000000
24,1.000000,1.000000,0.210648,1.000000,1.000000,0.086534,0.565878,6.113498e-01,0.210648,3.099820e-01,0.270787,4.585088e-01,0.000000,1.000000,0.441844,1.000000
31,1.000000,1.000000,1.000000,0.200000,1.000000,1.000000,1.000000,5.076340e-01,1.000000,5.143571e-01,1.000000,4.855042e-01,1.000000,0.000000,1.000000,1.000000
34,1.000000,1.000000,0.292893,0.575736,1.000000,0.539713,1.000000,3.907282e-01,0.292893,3.818775e-01,0.278005,5.149287e-01,0.441844,1.000000,0.000000,0.292893
39,1.000000,1.000000,1.000000,0.400000,1.000000,1.000000,1.000000,6.307255e-01,1.000000,1.000000e+00,0.562405,1.000000e+00,1.000000,1.000000,0.292893,0.000000

In [55]:
movies_data[(movies_data["userId"] == 12) | (movies_data["userId"] == 23)]

      userId                               movie  rating
5         12                    Toy Story (1995)     4.0
11        23                    Toy Story (1995)     4.0
3728      12             Grumpier Old Men (1995)     3.0
4547      12  Father of the Bride Part II (1995)     2.0
5206      12                         Heat (1995)     3.0
6466      12                      Sabrina (1995)     3.0

## The End!!!